Add support for xbacklight on Linux
kevva/brightness pull request #11
Opened 2016-08-18 18:58 UTC by bencevans

Allows for changing the brightness without sudoing

Debian/Ubuntu users can install using `apt-get install xbacklight`

2017-04-24 09:15 UTC, sindresorhus requested changes

2017-04-24 09:15 UTC, sindresorhus commented on lib/linux-xbacklight.js
> +	return new Promise(function (resolve, reject) {
There's no need to wrap a promise in another promise.

2017-04-24 09:15 UTC, sindresorhus commented on lib/linux-xbacklight.js
> +var Promise = require('pinkie-promise');
This is no longer needed as this module targets Node.js 4 now.

2017-04-24 09:16 UTC, sindresorhus commented
What's the benefit of this over the existing Linux implementation?

2017-04-24 09:37 UTC, bencevans commented
Doesn't require sudo rights

2017-04-24 09:51 UTC, sindresorhus commented
But it does require a manual `apt-get install xbacklight`, which is also not very user-friendly. Any way you could bundle `xbacklight` in your module? I've done that in the past myself (https://github.com/sindresorhus/clipboardy/commit/e3404e7a27c5f9ec0d04d69c94e28faa0423715d), and seems to work fine.

2017-05-24 01:44 UTC, kevva commented
ping @bencevans

2017-05-24 08:42 UTC, bencevans commented
Shall try to take a look soon.

2018-10-22 14:02 UTC, bencevans commented
I'm no longer using this so shall close the pull-request.

2018-10-22 14:02 UTC, closed without merging